// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Planner.Models;
using System;

namespace Planner.Migrations
{
    [DbContext(typeof(PlannerContext))]
    [Migration("20171208230146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Planner.Models.Sacrament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClosingHymn");

                    b.Property<string>("Conducting");

                    b.Property<string>("Convocation");

                    b.Property<string>("FirstSpeaker");

                    b.Property<string>("Invocation");

                    b.Property<string>("OpeningHymn");

                    b.Property<string>("RestHymn");

                    b.Property<DateTime>("SacramentDate");

                    b.Property<string>("SacramentHymn");

                    b.Property<string>("SecondSpeaker");

                    b.Property<string>("ThirdSeaker");

                    b.HasKey("ID");

                    b.ToTable("Sacrament");
                });
#pragma warning restore 612, 618
        }
    }
}
